apiVersion: v1
kind: Service
metadata:
  # Se expone la API de despachos al exterior para posibilitar la comunicación con el frontend
  name: back-despachos-service
  namespace: examen
spec:
  type: LoadBalancer
  selector:
    app: back-despachos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080